### ISSUE TITLE
A B+Tree Data Structure Repo

### ISSUE THREAD

**Issue by begeekmyfriend** [clibs/clib#112]
Hi all,

I would like to contribute my repo [bplustree](https://github.com/begeekmyfriend/bplustree.git) to `clib` packages. It is a simple b+tree algorithm demo for basic key-value CRUD operations.

I wish I can do more things with this repo:

- It can currently process key-value pair only as integer type. May be we can extend it for more data types later.

- It cannot do real I/O operations but using malloc/free to fake it.

My personal capacity is limited. I wish we can work together to make it better. Any pull requests and suggestions are welcome.

BR,
Leo.

**Comment by yorkie** [comment]
> I would like to contribute my repo bplustree to clib packages. It is a simple b+tree algorithm demo for basic key-value CRUD operations.

Hi @begeekmyfriend your link to repo is wrong, the correct link is [here](https://github.com/begeekmyfriend/bplustree).

By the way, please follow the [article](https://github.com/clibs/clib/wiki/Explanation-of-package.json) to create a `package.json` under your project, so that others can use the store.

Thank you

**Comment by begeekmyfriend** [comment]
It is done. Thank you for your reminder.

**Comment by yorkie** [comment]
After checking your source, and quite unsure if this is proper for `clibs` users, because your repo is just for building to binary over being a library, maybe you should do:

1. split the main function to separate file like `bin/bplusdb`
2. update the `bin` field and build script to your `package.json`.
3. provide a header file `bplustree.h` to expose your APIs and include this file into `src`.

Now closing the issue because this is not clib-related. Thanks for your contribution.

**Comment by begeekmyfriend** [comment]
OK. By the way, how do I leave a note or make contribution to this project on Github rather than opening a new issue?

**Comment by yorkie** [comment]
What are you meaning by "this project"? If you want to submit a patch or add feature for [clib](https://github.com/clibs/clib), PR is very welcome :)

**Comment by begeekmyfriend** [comment]
I meant how could I contribute to `clib` packages, at least where should I leave a note rather than opening an issue?

**Comment by begeekmyfriend** [comment]
@yorkie Hey, I have made some changes to [bplustree](https://github.com/begeekmyfriend/bplustree.git) to make it more look like a library. I have added cmake for building scripts. Any suggestions are welcome.
