### ISSUE TITLE
add stb libraries to clib

### ISSUE THREAD

**Issue by erf** [clibs/clib#132]
I believe [splitting](https://github.com/nothings/stb/issues/247) up and adding the [stb](https://github.com/nothings/stb) libraries to clib would make a nice addition.

**Comment by erf** [comment]
[cpr](https://github.com/whoshuu/cpr) also seem fit for clib

**Comment by willemt** [comment]
You can split them out like this:

1. Create a blank repo for one stb library
2. Add package.json to the blank repo
3. Set the pacakge.json's ```repo``` key to "https://github.com/nothings/stb", and it's ```src``` key to the source files you want to include
4. Add the new repo to clib package list wiki

This is nice because it pulls from upstream.

See https://github.com/clibs/build_assert for an example

**Comment by erf** [comment]
I've added repo https://github.com/erf/stb and updated the Wiki, but i can't find the stb library when searching. Is there a delay or did i do something wrong?

**Comment by willemt** [comment]
I think there's a ```--skip-cache``` option (https://github.com/clibs/clib/pull/123)

**Comment by erf** [comment]
:+1:

**Comment by erf** [comment]
Let me know if you want me to transfer the repository to the clibs organization.
