### ISSUE TITLE
Dependency Manager NOT Package Manager

### ISSUE THREAD

**Issue by Yousha** [clibs/clib#144]
According to the Wiki definition(and SO answers), this **clibs** project is a **Dependency Manager**, not Package Manager.
Package Manager is used for SYSTEM and **Dependency Manager for PROJECT**

> WIKI: A package manager or package management system is a collection of software tools that automates the process of installing, upgrading, configuring, and removing computer programs for a computer's operating system in a consistent manner.

https://en.wikipedia.org/wiki/Package_manager
https://stackoverflow.com/a/27290095/1429432

**Comment by stephenmathieson** [comment]
Based on this, most other package managers (npm, pip, etc) are also wrong. I'm going to close this as I don't think anything productive will come of this discussion (seems like bikeshedding).

**Comment by jwerle** [comment]
:roll_eyes:

**Comment by Yousha** [comment]
Ok, but @stephenmathieson can you tell me what's the difference between **apt yum pacman rpm** AND **clib**?
While they installs Package and clibs installs a just Source Library?

**Comment by catb0t** [comment]
The difference IMO is that NPM, PyPi, CPAN, etc, all of which are used as both project dependency managers as well as installing system-wide libraries and binaries, whereas (as far as I know) CLib can only be used for installing packages locally, as binaries or source libraries, **not** system-wide (because CLib has no provisions for keeping track of installed packages on a system-wide scale, only per-project).

Given that argument I think it's obvious CLib is a dependency manager, and much less a package manager for any scope wider than individual projects.

**Comment by jwerle** [comment]
@catb0t @Yousha clib is both, or maybe *neither*. It can install dependency source files into a `deps/` directory as well as invoke a [build and install script provided in a `package.json` file](https://github.com/tj/watch/blob/master/package.json#L8) that installs a program into your system unaware of any project. We have a [list of executable](https://github.com/clibs/clib/wiki/Packages#executables) currently installable by `clib`. While clib lacks some of the core package manager functionality you might expect (updates, introspection, rollback, etc), it is still more than just a dependency manager.

IMHO, this conversation is counter productive. Instead of creating an issue to just call out what the project **isn't**, we should instead start a dialog about improving the project by detailing the things it should do cc @stephenmathieson
