### ISSUE TITLE
clib install nami-doc/trim.c fails due to the repo name format (trim.c)

### ISSUE THREAD

**Issue by laoshaw** [clibs/clib#156]
`clib install nami-doc/trim.c` will fail, however if I change nami-doc/trim.c to nami-doc/trim repo it will succeed, it seems to me clib has a bug, that if the repo name is the same as source code(e.g. trim.c) it will fail.

**Comment by stephenmathieson** [comment]
Something is definitely wrong here, but it's not due to the `.c` in the repo name. It looks like Clib is getting confused when fetching source files. It starts off grabbing files from the master branch, then attempts to grab tagged sources (`0.0.1`), but that tag doesn't exist (despite what package.json says).

Debug output:

```
∴ DEBUG=clib* clib install nami-doc/trim.c
 clib : args: nami-doc/trim.c
 clib : command 'install'
 clib : exec: /usr/local/bin/clib-install nami-doc/trim.c
 clib-install : 1 arguments
 clib-install : install nami-doc/trim.c (0)
 clib-package : creating package: nami-doc/trim.c
 clib-package : author: nami-doc
 clib-package : name: trim.c
 clib-package : version: master
       fetch : nami-doc/trim.c:package.json
 clib-package : GET https://raw.githubusercontent.com/nami-doc/trim.c/master/package.json
 clib-package : status: 200
 clib-package : creating package: vendethiel/trim.c
 clib-package : file: trim.c
 clib-package : file: trim.h
 clib-package : no dependencies listed in package.json
 clib-package : no development dependencies listed in package.json
 clib-package : mkdir -p ./deps/trim
 clib-package : write: ./deps/trim/package.json
 clib-package : fetch file: vendethiel/trim.c/trim.c
 clib-package : file URL: https://raw.githubusercontent.com/vendethiel/trim.c/0.0.1/trim.c
       fetch : vendethiel/trim.c:trim.c
       error : unable to fetch vendethiel/trim.c:trim.c
```

My guess is this is an issue with the `nami-doc/trim.c` repo, since Clib is able to install other packages just fine. I'll leave this open to dig into it later tho.

**Comment by PengZheng** [comment]
[Fixed](https://github.com/vendethiel/trim.c/issues/3#issuecomment-383529010)
