### ISSUE TITLE
The Packages List Should Be in its Own Repo

### ISSUE THREAD

**Issue by WestleyR** [clibs/clib#164]
The Packages List Should Be in its Own Repo. Heres why **I** this it should:

 - Easy to add to, by PRs. (I don't even know how to add to the wiki pages...)
 - Can clearly see all the changes.
 - Not limited to the wiki pages.

Of course this can be discussed, and decided by users. :+1: / :-1: 

*Not assigning myself to this one yet...*

**Comment by abranhe** [comment]
Why it should not be on its own repo?

It would be perfect to have a website and host the packages as #137 says but since we are not hosting it rn the best way is to keep it on the clib's wiki page.

Having a repo with a bunch of projects will bring a lot of pull requests.

For maintainers:

- They will need to review a lot of PRs and in other words, waste a lot of time

For users:

- You will need to **WAIT** that your PR gets merged in to be happy.

In the other hand clib wiki pages are editable by anyone, so just adding your package to your list it will appear on the `clib-search`.

If you don't know how to edit a wiki page, just go to https://wiki.github.com/clibs/clib, under Resources navigate to [Packages](https://github.com/clibs/clib/wiki/Packages) page:

On the top right you will have this:

<img width="171" alt="screen shot " src="https://user-images.githubusercontent.com/21347264/52906764-3cfc7b80-3221-11e9-9670-5a9e65b13107.png">

click on Edit, add your package and then search for your package. See and example that I created:

<img width="563" alt="shot" src="https://user-images.githubusercontent.com/21347264/52906777-86e56180-3221-11e9-9eea-c6ff980c6a51.png">

Lastly if we decide to move the wiki page to a new repo we will need to make a few changes to [`clib-search`](https://github.com/clibs/clib/blob/master/src/clib-search.c) you can still open a PR if you assume that would be easier for everyone.

---

A similar story happend with [buckaroo](https://github.com/loopperfect/buckaroo) (A C++ package manager). I am a Buckaroo contributor and we use to have a repository with all the Buckaroo recipes (https://github.com/LoopPerfect/buckaroo-recipes) almost impossible to maintain, but after buckaroo 2.0.0 a released 2 weeks ago we decided that all the packges are imported from the git repository address. Same issue here.

It could be that [Homebrew](https://github.com/Homebrew) that still have a repo with all their recipes but personally I don't think that a good thing.

**Comment by WestleyR** [comment]
Ohh, I didn't know the wiki pages can be edited by anyone... Thats a bit scary, IMO...

I see your point, yes there will be a lot of PRs, and depending on if all the packages are in one file, that could be a lot of conflict PR after PR...

Maybe theres a way to make the repo writable by users, so we can at least see when/what changes.

*I'm leaving this issue open for discussing.*

**Comment by WestleyR** [comment]
Alright! After some time to think about this, I'm kinda agreeing with @abranhe. I guess we will have to trust all **31 Million** github users :smile:
