### ISSUE TITLE
clib configure Segmentation fault when no arguments given

### ISSUE THREAD

**Issue by Isty001** [clibs/clib#199]
The configure subcommand crashes with a Segmentation fault when no arguments given.

```
Starting program: /usr/local/bin/clib configure
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 5282]
Segmentation fault (core dumped)
[Inferior 1 (process 5272) exited with code 01]
```

Unfortunately I'm not too familiar with the configure command. What should be the expected behavior when no arguments given?

**Comment by stephenmathieson** [comment]
I also didn't know there was a "configure" subcommand. I would expect it to print a "help" screen if it was not given required arguments.

**Comment by stephenmathieson** [comment]
I just built clib@master and ran `clib configure`. I don't know what it did. Here's the output:

```
➜  clib git:(master) clib configure
➜  clib git:(master)
```

I'm on macOS Catalina btw.

**Comment by stephenmathieson** [comment]
Here's the `--help` screen, which doesn't explain much either:

```
➜  clib git:(master) clib configure --help

  Usage: clib-configure [options] [name ...]

  Options:

    -V, --version                 output program version
    -h, --help                    output help information
    -o, --out <dir>               change the output directory [deps]
    -P, --prefix <dir>            change the prefix directory (usually '/usr/local')
    -q, --quiet                   disable verbose output
    -d, --dev                     configure development dependencies
    -f, --force                   force the action of something, like overwriting a file
    --cflags, --flags                   output compiler flags instead of configuring
    -c, --skip-cache              skip cache when configuring
    -C, --concurrency <number>    Set concurrency (default: 4)
```

**Comment by jwerle** [comment]
looks like the dep from the installed [clib-package](https://github.com/clibs/clib/tree/master/deps/clib-package) requires the `http-get` dep at the `next` tag, which doesn't exist since we transferred the repo. Updating it with `clib i -fcd` seems to fix the issue: https://github.com/clibs/clib/commit/baba71f7a812420e2d27e6f596f520cb6148094c

The `clib-configure` command executed without arguments will execute a `configure` script for each dep installed, if they define one, like [here](https://github.com/jwerle/libmerkle/blob/master/clib.json#L7)

`clib-configure [name ...]` will execute a configure script for deps by name

**Comment by jwerle** [comment]
Sorry for not documenting this (and the other commands...) I need to get around to doing it

**Comment by stephenmathieson** [comment]
Oh, very cool! I think this will be super useful once we sort the bugs out!

**Comment by Isty001** [comment]
Thanks! It seems to be working now!
