### ISSUE TITLE
Make the default user/org configurable

### ISSUE THREAD

**Issue by stephenmathieson** [clibs/clib#214]
It might be nice to let users control the default user/org name when installing packages. Today when you do `clib install foo`, the `clibs/foo` package is installed. This feature would let you control that behavior and replace `clibs/` with `yourusername/`.

Not sure where we'd persist this tho, as we currently have no "global state". Maybe create `$HOME/clibrc.json` or something?

**Comment by Isty001** [comment]
I really like the idea of having a config file to override some default behavior, but I think this exact option could break some packages.

If the default org is changed, then packages in the dependency chain which already reference something like `hash` will be resolved to `yourusername/hash` instead of `clibs/hash`,

**Comment by jwerle** [comment]
I echo @Isty001 on this one. I also do think we need a global config!

**Comment by stephenmathieson** [comment]
@Isty001 that's a great point, I didn't think about that.

**Comment by Isty001** [comment]
Closing this one, but opened #220 for the global config file.
