### ISSUE TITLE
Automatically Add Dependencies to clib.json when clib install is called.

### ISSUE THREAD

**Issue by phoenixpinpoint** [clibs/clib#291]
One of the things I have noticed is dependencies are not added to clib.json when clib install is called. This would make this easier to use than it already is.

**Comment by exbotanical** [comment]
I looked at the clib code because I wanted to implement this and found that the feature is already there. Run install with the `-S` or `--save` flag.

Seems this behavior was inspired by npm, which as of v5 saves deps to package.json by default ([ref](https://blog.npmjs.org/post/161081169345/v500)). Nowadays npm supports `--no-save` (or `-no-` prepended to pretty much any flag) to negate the behavior. 

This makes more sense to me as a default behavior. If the maintainers are good with it, I'll make the change.

**Comment by jwerle** [comment]
> I looked at the clib code because I wanted to implement this and found that the feature is already there. Run install with the `-S` or `--save` flag.
> 
> Seems this behavior was inspired by npm, which as of v5 saves deps to package.json by default ([ref](https://blog.npmjs.org/post/161081169345/v500)). Nowadays npm supports `--no-save` (or `-no-` prepended to pretty much any flag) to negate the behavior.
> 
> This makes more sense to me as a default behavior. If the maintainers are good with it, I'll make the change.

yeah we'd happily review a PR for this!
