### ISSUE TITLE
Different name than package.json?  clib.json?

### ISSUE THREAD

**Issue by mbucc** [clibs/clib#85]
I guess there is Arduino packaging util called leo that uses the same name.  No idea how prevalent or widespread it is used.

@AdamMagaluk added a package.json to his fork of the c library js0n.  When I first saw that, I though cool, he already packaged it up for clib.  :)   (https://github.com/quartzjer/js0n/network)

**Comment by Potherca** [comment]
I'm looking at this topic in https://github.com/bpkg/bpkg/issues/17. The main issue for me is that `package.json` is _not_ universal. 

Specifically, dependencies that might exist in one language/stack most likely do not in others.

The approach I'm suggesting for BPKG might also be relevant here...

Instead of support on or the other, support both but give the more specific name priority over the generic on.

- if a project has only a `package.json`, that is used
- if a project has only a `clib.json`, that is used
- if a project has both a `package.json` _and_ a `clib.json`, the  `clib.json` is used

**Comment by jwerle** [comment]
@stephenmathieson reopening for now as this discussion has kicked been kicked off again for `bpkg`. Github's support for the "Used by" feature on repository pages makes this conflict more visible.

Consider https://github.com/jwerle/fs.c which says it is "used by" over *131k* packages. Obviously this is not true and must refer to the `fs` module being required or worse, https://www.npmjs.com/package/fs

What are your thoughts on this? Happy to issue a PR to `clib-package`

**Comment by netpoetica** [comment]
My initial comments were from quite a long time ago when package.json was reasonably small and simple enough (npm version obviously) to have gone the "universal package descriptor" route. I would confess that package.json has become much more tightly coupled with npm/node in general and that my childish, utopian dream won't hold up :)
